_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: torch.load
    f: /home/sm/PycharmProjects/dynamo_ssl/exp_local/for_examination/res18_clean_rollout200/encoder_9.pt  # set the path to the encoder snapshot here
normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 512