_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: torch.load
    f: /home/sm/PycharmProjects/dynamo_ssl/exp_local/2024.12.16/000735_train_pusht_rollout_dynamo_headless/encoder_12.pt  # set the path to the encoder snapshot here
normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 512