_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: torch.load
    f: '/data/dynamo/dynamo-weights/pusht_pretrained_state_dict.pt'  # set the path to the encoder snapshot here
normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 512