_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: models.encoder.resnet.resnet18
    pretrained: False
    output_dim: 512
    unit_norm: False


normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 512

# 384 for ViT-S.
# 768 for ViT-B.
# 1024 for ViT-L.
# 1536 for ViT-g.